/** 
 * status.Java
 * Enum used to display different pages or states of the game
 * @author Christopher Lo
 * @version 1.0
 * June 2021
 */

public enum status {
    MAIN,
    STATS,
    CHANGE_TEAM,
    CHANGE_MOVES,
    POKEMON_SELECTION,
    MOVE_SELECTION,
    MOVE_LIST,
    POKEMON_SCREEN,
    CHANGE_PLAYER_POKEMON,
    CHANGE_OPPONENT_POKEMON,
    PICKAMOVE, 
    PLAYERMOVE, 
    OPPONENTMOVE, 
    FAINTED, 
    MISSED,
    SUPEREFFECTIVE, 
    NOTEFFECTIVE, 
    NOEFFECT, 
    FLINCH,
    ATTACK_ROSE,
    ATTACK_SHARPLY,
    DEFENSE_ROSE,
    DEFENSE_SHARPLY,
    SPEED_ROSE,
    SPEED_SHARPLY,
    SPECIAL_ATTACK_ROSE,
    SPECIAL_ATTACK_SHARPLY,
    SPECIAL_DEFENSE_ROSE,
    SPECIAL_DEFENSE_SHARPLY,
    ATTACK_CANT_CHANGE,
    DEFENSE_CANT_CHANGE,
    SPEED_CANT_CHANGE,
    SPECIAL_ATTACK_CANT_CHANGE,
    SPECIAL_DEFENSE_CANT_CHANGE,
    PLAYER_HURT,
    OPPONENT_HURT,
    ALREADY_HAS_STATUS_CONDITION,
    FAILED,
    BURN,
    PARALYZED,
    FROZEN,
    POISONED,
    YOU_LOST,
    YOU_WON;
}